osx_image: xcode7.3
language: objective-c
before_install:
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/IBentifiers.xcworkspace -scheme IBentifiers-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- travis_wait pod lib lint
